### ISSUE TITLE
Failed to install platform: 'Inkplate_Boards:esp32:8.0.0' with Arduino IDE 2.3.2

### ISSUE THREAD

**Issue by gmacario** [SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE#16]
Hello,

I wanted to install the Board support for the Inkplate5 board on an up-to-date installation of Arduino IDE 2.3.2 running on Windows 10.

I followed the instructions at https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE

1. Add URL: <https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/package_Dasduino_Boards_index.json> to "Additional Boards Manager" in your Arduino IDE Preferences
2. Install new boards via Tools -> Board -> Boards Manager. Type "dasduino" or "inkplate" in search box and pick the board you want to install.
3. Wait a bit.

but got the following error:

```text
Failed to install platform: 'Inkplate_Boards:esp32:8.0.0'.
Error: 13 INTERNAL: Cannot install platform: installing platform Inkplate_Boards:esp32@8.0.0: testing local archive integrity: testing archive size: fetched archive size differs from size specified in index: 73187083 != 73187087
```

**Comment by rsoric** [comment]
Hi @gmacario , sorry for the delayed reply.

Could you please try Arduino IDE legacy? It usually works well, we find that Arduino IDE 2> has problems with our board definitions. This should fix the issue. If not, could you try the dev branch of that board definition? Simply replace 'master' with 'dev' in that board manager URL.

**Comment by rsoric** [comment]
Closing as there's no more activity, please re-open the issue if you reach the same problem.
