### ISSUE TITLE
Property 'upload.tool.serial' is undefined 

### ISSUE THREAD

**Issue by gemby** [SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE#18]
I had issue while programming DasduinoCore ( i got it as a gift in DORS Cluc 2024, thank you ;-) in Arduino IDE ( Version: 2.3.2 ) it compiles without issues, but it keeps saying "Property 'upload.tool.serial' is undefined" regardless what programer i have put.  I searched a bit, and it seems that this version of Arduino IDE is looking for default programming method. So i added below
core.upload.tool=avrdude
this:
core.upload.tool.default=avrdude

Restarted Arduino IDE and it compiles and uploads to board without issues.

/Users/username/Library/Arduino15/packages/Dasduino_Boards/hardware/avr/2.0.0/boards.txt

OS: OSX Sonoma, Mac Mini M1
IDE: Arduino IDE Version: 2.3.2

**Comment by rsoric** [comment]
Hi @gemby ,

we've had some issues with the board definitions on Arduino 2.0 and newer. Could you try the old Arduino? You can find the software [here](https://www.arduino.cc/en/software/OldSoftwareReleases/). 

Of course the editor isn't as good but you can also always try the [Arduino extension for VSCode](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino). 

If none of these work, you may have to delete Arduino cache:

1. Close the Arduino IDE: Ensure the Arduino IDE is not running.
2. Open Finder: Launch Finder from the Dock.
3. Go to the Library Folder: Press Cmd + Shift + G, type ~/Library, and press Enter.
4. Navigate to Arduino15 Folder: Open the Arduino15 folder inside the Library.
5. Delete Cached Boards: Delete the packages folder to remove all cached board definitions.
6. Delete General Cache: Delete the cache folder to clear the general cache.
7. Restart the Arduino IDE: Open the Arduino IDE again; it will recreate necessary folders and files.

Give these a try and please let me know if it's working here, we'll see from there.,

-Rob

**Comment by gemby** [comment]
Thank you, it is working, but it is also working with Arduino 2.x  if you add  this:
`core.upload.tool.default=avrdude`
in boards.txt

**Comment by rsoric** [comment]
Thank you @gemby 

@BornaBiro, have a look at this please

**Comment by BornaBiro** [comment]
@gemby @rsoric This is fixed in Dasduino AVR Boards v2.0.1. which is currently live. Try to update it and see if the same problem still exists.
